# Generated by Django 3.0.6 on 2020-05-27 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
            ],
            options={
                'ordering': ('type', 'count'),
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('size',),
            },
        ),
        migrations.CreateModel(
            name='Stitcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_profile', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': (django.db.models.expressions.F('user.last_name'), django.db.models.expressions.F('user.first_name')),
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField()),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='stitchitapi.Stitcher')),
                ('stitcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followees', to='stitchitapi.Stitcher')),
            ],
            options={
                'ordering': (django.db.models.expressions.F('stitcher.user.last_name'), django.db.models.expressions.F('stitcher.user.first_name')),
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255, null=True)),
                ('completed_date', models.DateTimeField(null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='design/images/')),
                ('fabric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stitchitapi.Fabric')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stitchitapi.Size')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stitchitapi.Stitcher')),
            ],
            options={
                'ordering': ('completed_date',),
            },
        ),
    ]
