# Generated by Django 3.0.6 on 2020-06-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stitchitapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='user',
            new_name='stitcher',
        ),
    ]
